name: "listen.dev Dependency Scan"
description: "Get real-time dependency insights in Pull Requests 🐬"
author: "The listen.dev team <engineering@garnet.ai>"
inputs:
  token:
    description: "The GitHub API token."
    required: true
    default: ${{ github.token }}
  lstn:
    description: "The lstn CLI version."
    required: false
    default: "latest"
  workdir:
    description: "Working directory relative to the root directory."
    required: false
    default: "."
  reporter:
    description: "Preferred reporting mechanisms (gh-pull-comment,gh-pull-review,gh-pull-check)"
    required: false
    default: "gh-pull-comment"
  lstn_flags:
    description: "Additional lstn CLI flags"
    required: false
    default: ""

runs:
  using: "node16"
  main: "dist/index.js"
branding:
  color: "green"
  icon: "alert-octagon"