name: "listen.dev"
description: "Proactive Security Monitoring Inside GitHub Actions."
author: "The listen.dev team <engineering@garnet.ai>"
inputs:
  token:
    description: "The GitHub API token."
    required: true
    default: ${{ github.token }}
  jwt:
    description: "The listen.dev JWT token."
    required: false
    default: ""
  lstn:
    description: "The lstn CLI version."
    required: false
    default: "latest"
  ci:
    description: "Whether to run the CI eavesdrop tool or not. It works with the listen.dev JWT token."
    required: false
    default: "false"
  workdir:
    description: "Working directory relative to the root directory."
    required: false
    default: "."
  config:
    description: "The path of the configuration file."
    required: false
    default: ""
  reporter:
    description: "Preferred reporting mechanisms (gh-pull-comment,gh-pull-review,gh-pull-check,pro)"
    required: false
    default: "gh-pull-comment"
  select:
    description: "JSONPath script expression to filter the output verdicts"
    required: false
    default: ""
  lstn_flags:
    description: "Additional lstn CLI flags"
    required: false
    default: ""
  eavesdrop_version:
    description: "Use a custom version of our CI eavesdrop tool"
    required: false
    default: ""

runs:
  using: "node20"
  main: "dist/index.js"
  post: "dist/index.js"

# https://actions-cool.github.io/github-action-branding/
branding:
  icon: 'shield'
  color: 'green'
