name: "Scan your dependencies with the listen.dev CLI"
description: "Get real-time dependency insights in your pull requests 🐬"
author: "The listen.dev team <engineering@garnet.ai>"
inputs:
  token:
    description: "The GitHub API token."
    required: true
    default: ${{ github.token }}
  lstn:
    description: "The lstn version."
    required: false
    default: "latest"
  workdir:
    description: "Working directory relative to the root directory."
    required: false
    default: "."
  reporter:
    description: "One or more reporting mechanisms (gh-pull-comment,gh-pull-review,gh-pull-check)"
    required: false
    default: "gh-pull-comment"
  lstn_flags:
    description: "Additional lstn flags"
    required: false
    default: ""

runs:
  using: "node16"
  main: "dist/index.js"
branding:
  color: "green"
  icon: "alert-octagon"