name: 'CLA assistant'

on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]

jobs:
  CLAAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: 'CLA Assistant'
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        uses: contributor-assistant/github-action@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          path-to-signatures: '.github/cla/signatures.json'
          path-to-document: 'https://github.com/listendev/.github/blob/main/.github/cla/ICLA.md'
          remote-organization-name: listendev
          remote-repository-name: .github
          branch: 'main' # must not be protected
          allowlist: github-actions*,dependabot*
          create-file-commit-message: 'docs: store CLA signature'
          signed-commit-message: 'docs: $contributorName has signed the CLA in action#$pullRequestNo'
          # use-dco-flag: true # Set this to true if you want to use a dco instead of a CLA
