name: listendev

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  development:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Self inspect ourselves
      - uses: ./
        with:
          runtime: true
          jwt: ${{ secrets.LISTENDEV_TOKEN }}

      - name: Debug
        run: |
          sudo cat /var/run/jibril/default

      - name: Setup Node.JS
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run prettier
        run: npm run format-check

      - name: Run linter
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Test
        run: npm test
