name: distribution

# This workflow ensures that the generated contents of the dist directory match what they are expected to be.
# For actions that follow our TypeScript or JavaScript templates, dist contains the packaged script that is executed by the runner.
# Whenever you update the source code, the dist files must be regenerated for the changes to take effect.

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  distribution:
    uses: actions/reusable-workflows/.github/workflows/check-dist.yml@main
