name: validation

# This workflow compiles and tests the code in the repo. It also checks that it passes linting and formatting rules. 
# Optionally, it can run npm audit on the packages in the repo.

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  basic:
    uses: actions/reusable-workflows/.github/workflows/basic-validation.yml@main
